[package]
name = "schrage"
version = "0.1.0"
edition = "2021"

[lib]
name = "schrage"
path = "src/lib.rs"

[dependencies]
heap = { path = "../heap" }

[dev-dependencies]
lazy_static = "1.4.0"
paste = "1.0.12"